version: "3.8"

services:
  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER:-baserow}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?}
      - POSTGRES_DB=${DATABASE_NAME:-baserow}
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "su postgres -c \"pg_isready -U ${DATABASE_USER:-baserow}\""
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      local:
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    command: redis-server --requirepass ${REDIS_PASSWORD:?}
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    networks:
      local:


volumes:
  pgdata:


networks:
  local:
    driver: bridge
